-- Jemima Foreman, an applicant called us, that her phone number changed to: 003670/223-7459
-- Write an UPDATE query, that changes this data in the database for this applicant.
-- Also, write a SELECT query, that checks the phone_number column of this applicant.
-- Use both of her name partsin the conditions!
